// One-off: wrap spike/sample.html into spike/device/htmlContent.ts
// so the app is fully offline (mirrors the real app: HTML built in-memory).
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, 'sample.html'), 'utf8');
const out = '// AUTO-GENERATED by spike/embed-html.js from spike/sample.html — do not edit.\n'
  + 'export const SAMPLE_HTML: string = '
  + JSON.stringify(html)
  + ';\n';
fs.writeFileSync(path.join(__dirname, 'device', 'htmlContent.ts'), out);
console.log('htmlContent.ts written:', (out.length / 1024).toFixed(1), 'KB');
